### ISSUE TITLE
Deserializer trouble with const(T[])[] struct fields

### ISSUE THREAD

**Issue by david-eckardt-sociomantic** [sociomantic-tsunami/ocean#79] opened 2017-04-18 18:29 UTC
`Deserializer` does not correctly deserialise `const(T[])[]` struct fields. The problem is a qualifier-incompatible way of checking for a dynamic array in [`sliceSubArrays`](https://github.com/sociomantic-tsunami/ocean/blob/v2.x.x/src/ocean/util/serialize/contiguous/Deserializer.d#L1050-L1052).
For the reference type qualifier inexperienced, this is how it fails:
```d
alias const(char[])[] T;
// Check if T is an array, and if so, derive the element type:
static if (is (T V : V[]))
{
    // V is const(char)
    // Now check if T is a dynamic array:
    static if (is(V[] == T)) // compares const(char)[] with const(char[]) -- not the same
    { /* ... */ }
    else
    { /* False negative, T is a dynamic array. */ }
}
```
So far so good, this can be fixed. But then another problem occurs: [`sliceSubArrays`](https://github.com/sociomantic-tsunami/ocean/blob/v2.x.x/src/ocean/util/serialize/contiguous/Deserializer.d#L1056) cannot call [`sliceArray`](https://github.com/sociomantic-tsunami/ocean/blob/v2.x.x/src/ocean/util/serialize/contiguous/Deserializer.d#L907) because the `out` parameter of `sliceArray` would need to be the array element type `const(char[])` -- which is illegal, an `out` parameter cannot be `const`.
This conflict is a symptom of a more fundamental problem with deserialising `const`. Given a struct
```d
struct S
{
    const(T[]) a;
}
```
What the deserialiser essentially does is the following:
```d
void[] input_data;
void[] slices_buf;
S dst;
dst.a = cast(const(T[]))(slices_buf[
    0 .. numberOfElements(input_data) * const(T[]).sizeof
]);
foreach (ref element; dst.a)
{
    element = deserialiseNextElement(data);
}
```
The problem here is that the assignment in the `foreach` loop is illegal because `typeof(element)` is `const(T[])` -- one cannot assign to `const`.
So what can we do here? The only options that come to my mind is to either ban such a `const` or cast it away when populating the array, considering `slices_buf` to be uninitialised memory.

Any ideas, anyone?

**Comment by mihails-strasuns-sociomantic** [comment] 2017-04-22 09:32
Currently by design it should not be legal at all to deserialize into struct with any `const` fields - I am surprised (and worried) it compiles at all. Intended pattern would be to serialize struct as const but to deserialize as mutable - otherwise deserializer would have to blindly agree to mutating `const` field.

What was original code that has triggerred the issue?

**Comment by david-eckardt-sociomantic** [comment] 2017-04-24 11:38
> I am surprised (and worried) it compiles at all.

Yes, unfortunately it did compile and just silently skipped the `const` fields, producing garbage.
What exactly would it be a problem to deserialise structs with `const` fields? After all `const` only means one cannot change it through this name, not that it will never change (in fact it won't unless you modify the referenced buffer with serialised data, which you shouldn't).
Or is it about losing `const` transitivity and having a `const` struct field referring to the mutable serialised data?

**Comment by mihails-strasuns-sociomantic** [comment] 2017-04-24 12:03
> What exactly would it be a problem to deserialise structs with const fields?

It was combination of two points:

1) Adding `const` support increases maintenance complexity considerably. As long as contiguous property is not violated, it should not be possible to trigger UD this way (because underlying data buffer is always mutable) but it is something that needs to be kept in mind for every single change as type system does not protect you here (we cast everything to plain `void[]`).
2) It is not necesessary per se, because deserialized data is guaranteed to always be mutable. It may be needed to serialize something immutable but once it gets back it is always mutable.

Now if we won't find reasonable design for swarm that works with struct head-`const`, we may need to do it anyway - but I'd prefer to keep it as option of last resort because of its impact.

**Comment by david-eckardt-sociomantic** [comment] 2017-04-24 12:43
> Adding `const` support increases maintenance complexity considerably.

True, but `const` support needs to be added at least in the way that it is detected and rejected. Without handling `const` in any way the deserialiser  produces garbage. In  #80 the actual complication and increased maintenance burden is the code which detects `const` while handling it after it hast been detected is relatively simple: Just cast it away.
A radically simple alternative would be to check the whole struct at once using something like
```d
static assert(__traits(compiles, {S s;}), S.stringof ~ " contains const somewhere");
```
but that would at least not be very helpful for the user (and could probably be triggered by other conditions than `const` such as an explicit struct constructor).

**Comment by mihails-strasuns-sociomantic** [comment] 2017-04-24 12:46
Yeah, rejecting such structs is a must of course, existing situation is unacceptable. I will create a separate PR just for that.

**Comment by david-eckardt-sociomantic** [comment] 2017-04-24 12:48
I could change #80 to reject `const` if detected rather than handling it.

**Comment by david-eckardt-sociomantic** [comment] 2017-04-24 12:49
But my main point is complexity/maintenance burden, which wouldn't change. Would you rather do a whole-struct check using `__traits(compiles)` or something similar?

**Comment by mihails-strasuns-sociomantic** [comment] 2017-04-24 12:57
I don't think simple whole-struct check is possible for our case (for example, it will pass if structs contains `cstring`), my intended approach was to add dedicated `ocean.core.Traits` template, `containsQualified` which may or may not return qualified field name (I don't mind either way).

**Comment by david-eckardt-sociomantic** [comment] 2017-04-24 13:07
I'm not sure if this is much better: `containsQualified` would just do the exact same type recursion as the serialiser. (In fairness, this is the case for `ContainsDynamicArray` as well, so it could be a good idea.)

**Comment by david-eckardt-sociomantic** [comment] 2017-04-24 13:11
Hm, isn't `isPOD` what we really want? There are even more D2 struct features that should be rejected, disabled post-blit or struct constructors for example.

**Comment by mihails-strasuns-sociomantic** [comment] 2017-04-24 13:20
True, repeating type recursion is annoying but in my opinion it is much easier to maintain bunch of  highly specialized recursions than one generic one (i.e. we duplicate it in `Contiguous` invariant already).

What is the definition of `isPOD` you refer to? I don't see one in ocean.

**Comment by david-eckardt-sociomantic** [comment] 2017-04-24 13:29
[`__traits(isPOD)`](http://dlang.org/spec/traits.html#isPOD) -- IIRC a struct without construction or copying constraints and only mutable fields (not sure if POD means the latter as the documentation doesn't define POD).

**Comment by mihails-strasuns-sociomantic** [comment] 2017-04-24 13:32
I don't think that trait cares about mutability at all : https://dpaste.dzfl.pl/6602096c8053

**Comment by david-eckardt-sociomantic** [comment] 2017-04-24 13:33
Ok, but non-POD should be rejected as well, shouldn't it?

**Comment by mihails-strasuns-sociomantic** [comment] 2017-04-24 13:35
http://dlang.org/glossary.html#pod seems to match our goals, but I would only commit it after trying out with bunch of structs we serialize :)

**Comment by mathias-lang-sociomantic** [comment] 2017-04-24 13:40
> http://dlang.org/glossary.html#pod seems to match our goals, but I would only commit it after trying out with bunch of structs we serialize :)

Initialized and copied. I think that means 'copied from', so a `struct` including non-mutable element fall under this definition as well.

**Comment by david-eckardt-sociomantic** [comment] 2017-04-24 15:38
> Refers to a struct that contains no hidden members, does not have virtual functions, does not inherit, has no destructor, and can be initialized and copied via simple bit copies.

Think of all the struct inheritance with virtual functions we have in our code base.

**Comment by david-eckardt-sociomantic** [comment] 2017-04-24 16:38
I'm still not entirely sure about whether support to reject `const` struct fields. IIUC type system wise supporting it is fine so the reason for rejecting it would be to avoid additional complexity and the higher maintenance burden. Is this a good reason? I wonder:
- The `const` support code is already in #80.
- The complexity is already high; looking at the code I don't think `const` support unreasonably increases it. IMHO maintaining this code requires the same amount of focus and awareness either way.
- W.r.t. the last point: While adding `const` support I found several `const`-unrelated bugs which have been in there for ages, and no maintainer (including myself) has spotted them so far -- yet this code is heavily used in production where these bugs were simply never triggered. For years this code is practically considered to be mature -- turns out it wasn't, but it was mature enough for production so far.

So we can have the convention that the idea of serialising a struct containing `const` fields it is an unusual thing to do, yet it would be legal so to me it doesn't necessarily mean the `const` support code in the serialiser should be ripped out.

**Comment by mihails-strasuns-sociomantic** [comment] 2017-05-16 08:50
Closing as we agreed to not support deserializing into `const` fields for now.

**Closed as completed by mihails-strasuns-sociomantic** 2017-05-16 08:50 UTC
Labels: type-bug, res-wontfix
