### ISSUE TITLE
Duplicate definition of VersionHandlingException

### ISSUE THREAD

**Issue by mathias-lang-sociomantic** [sociomantic-tsunami/ocean#491] opened 2018-04-16 14:27 UTC
> ocean.util.serialize.contiguous.MultiVersionDecorator.VersionHandlingException at ./submodules/ocean/src/ocean/util/serialize/contiguous/MultiVersionDecorator.d(347) conflicts with ocean.util.serialize.model.VersionDecoratorMixins.VersionHandlingException at ./submodules/ocean/src/ocean/util/serialize/model/VersionDecoratorMixins.d(423)

Only in v4.x.x:
https://github.com/sociomantic-tsunami/ocean/blob/v4.0.5/src/ocean/util/serialize/model/VersionDecoratorMixins.d?utf8=%E2%9C%93#L423
https://github.com/sociomantic-tsunami/ocean/blame/v4.0.5/src/ocean/util/serialize/contiguous/MultiVersionDecorator.d#L347

Introduced by https://github.com/sociomantic-tsunami/ocean/commit/5e712a8f45ce2f682d434d6d6343fac2a181580d

I think it should be made an alias in a patch release, to at least fix the ambiguity.

**Comment by mihails-strasuns-sociomantic** [comment] 2018-04-16 15:57
I'd rather simply deprecate `VersionDecoratorMixins` - I simply forgot to remove it as part of v4.0.0, it is not used anywhere.

**Comment by mihails-strasuns-sociomantic** [comment] 2018-04-18 09:02
Actually already done in v4.x.x - 562f5a17ea7b3e0519ec5c8747b1f5bf5a7c81aa

**Comment by mihails-strasuns-sociomantic** [comment] 2018-04-18 09:03
Duplicate of https://github.com/sociomantic-tsunami/ocean/pull/469

**Closed as completed by mihails-strasuns-sociomantic** 2018-04-18 09:03 UTC
Labels: res-duplicate
