### ISSUE TITLE
The same file gets registered with ReopenableFilesExt multiple times

### ISSUE THREAD

**Issue by gautam-kotian-sociomantic** [sociomantic-tsunami/ocean#483] opened 2018-04-04 17:44 UTC
If the config file contains something like:
```
[LOG.file_a]
file = log/app_data.log

[LOG.file_b]
file = log/app_data.log
```
then the file `app_data.log` gets registered multiple times with the `ReopenableFilesExt` extension.

This results in the file also being reopened multiple times after rotation.

**Comment by gautam-kotian-sociomantic** [comment] 2018-04-04 17:48
One may argue that the configuration shown in the issue description above is incorrect, but my actual case is that I have an application which reloads its configuration on receipt of a signal. This results in log files being registered with the `ReopenableFilesExt` extension each time the config is reloaded (and thus reopened as many times as the signal was received).

**Comment by mihails-strasuns-sociomantic** [comment] 2018-04-05 08:51
This was supposed to be fixed in https://github.com/sociomantic-tsunami/ocean/pull/434

**Comment by nemanja-boric-sociomantic** [comment] 2018-04-06 15:02
Which version of the Ocean are you using @gautam-kotian-sociomantic ? The fix for this was released in v3.6.4, v3.7.1 and v4.0.1.

**Comment by gautam-kotian-sociomantic** [comment] 2018-04-09 16:01
I'm using ocean v3.7.3.

**Comment by nemanja-boric-sociomantic** [comment] 2018-04-10 15:50
There seems to be another regression with the #434 - it seems that if there are several loggers using the same _file name_, but different _file descriptors_ and you reopen the file, you'll just reopen the first instance of it - not all the file descriptors.

**Comment by nemanja-boric-sociomantic** [comment] 2018-04-10 15:51
So I think the #434 is invalid and should be reverted, but also this issue is kinda invalid - you should have an instance of the file registered in the `ReopenableExt` for each `Appender`.

**Comment by nemanja-boric-sociomantic** [comment] 2018-04-10 15:52
(I may not be completely right - I see the files are reused, I'll look into this tomorrow.)

**Comment by nemanja-boric-sociomantic** [comment] 2018-04-12 10:26
> There seems to be another regression with the #434 - it seems that if there are several loggers using the same file name, but different file descriptors and you reopen the file, you'll just reopen the first instance of it - not all the file descriptors.

I can confirm #434 is not the reason why the same file is opened twice:


With ocean v3.7.0:

```
app 6113 nemanjaboric    9w      REG              253,1      100 25036824 /home/nemanjaboric/work/app/staging/log/root.log
app 6113 nemanjaboric   10w      REG              253,1      100 25036824 /home/nemanjaboric/work/app/staging/log/root.log
app 6113 nemanjaboric   11w      REG              253,1     5021 25036825 /home/nemanjaboric/work/app/staging/log/version.log
app 6113 nemanjaboric   12w      REG              253,1     2400 25036826 /home/nemanjaboric/work/app/staging/log/stats.log
app 6113 nemanjaboric   13w      REG              253,1      100 25036824 /home/nemanjaboric/work/app/staging/log/root.log
app 6113 nemanjaboric   57w      REG              253,1        0 25036830 /home/nemanjaboric/work/app/staging/log/bidding.log
app 6113 nemanjaboric   74w      REG              253,1     4368 25036831 /home/nemanjaboric/work/app/staging/log/client_stats.log
```

**Comment by nemanja-boric-sociomantic** [comment] 2018-04-12 10:27
Hm, looks like with the ocean v3.7.0 it opens `root.log` three times. With v3.7.1 it opens it two times, so #434 clearly helps a bit ;-)

**Comment by nemanja-boric-sociomantic** [comment] 2018-04-12 10:38
OK, it's the application's fault - it's creating new Appenders in the `processConfig` override.

**Comment by nemanja-boric-sociomantic** [comment] 2018-04-12 10:52
As for the original report, @gautam-kotian-sociomantic I'm not able to reproduce this. Maybe we can take a look together this afternoon?

**Comment by mihails-strasuns** [comment] 2018-07-31 10:12
Closing in absence of reproducible test case. Please reopen if still present.

**Closed as completed by mihails-strasuns** 2018-07-31 10:12 UTC
Labels: type-bug, res-invalid
